[package]
name = "audiometa"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
symphonia = { version = "0.5.4", features = ["all", "all-formats", "all-codecs"] }
symphonia-metadata = "0.5.4"
convert_case = "0.4"
serde_json = "1.0"
walkdir = "2.0"