name: Rust Compile Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  actions: write
jobs:
  release:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
          - os_name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - uses: actions/checkout@v3
      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@614e479169873f012c973d243d5a5f80006b7438
        with:
          executable-name: audiometa
          target: ${{ matrix.platform.target }}
